# Generated by Django 2.1.1 on 2018-11-21 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Afili',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=2, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('ind_poder_aum', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
            ],
            options={
                'db_table': 'afili',
            },
        ),
        migrations.CreateModel(
            name='Catego',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=2, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('descrip', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'catego',
            },
        ),
        migrations.CreateModel(
            name='Combat',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=2, primary_key=True, serialize=False)),
                ('fech', models.DateField()),
                ('etp', models.DecimalField(decimal_places=0, max_digits=1)),
                ('ganador', models.DecimalField(blank=True, decimal_places=0, max_digits=1, null=True)),
                ('dura_min', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
            ],
            options={
                'db_table': 'combat',
            },
        ),
        migrations.CreateModel(
            name='Destr',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=2, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('descrip', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'destr',
            },
        ),
        migrations.CreateModel(
            name='Even',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=2, primary_key=True, serialize=False)),
                ('fech_in', models.DateField()),
                ('fech_fin', models.DateField()),
                ('dura', models.DecimalField(decimal_places=0, max_digits=2)),
            ],
            options={
                'db_table': 'even',
            },
        ),
        migrations.CreateModel(
            name='Habili',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=2, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=4)),
                ('valor', models.DecimalField(decimal_places=0, max_digits=1)),
            ],
            options={
                'db_table': 'habili',
            },
        ),
        migrations.CreateModel(
            name='Inscri',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=2, primary_key=True, serialize=False)),
                ('n_grupo', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
                ('punto_etp1', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
                ('campeon', models.BooleanField(blank=True, null=True)),
                ('descrip', models.CharField(blank=True, max_length=300, null=True)),
                ('fk_even', models.ForeignKey(db_column='fk_even', on_delete=django.db.models.deletion.DO_NOTHING, to='marvel.Even')),
            ],
            options={
                'db_table': 'inscri',
            },
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=2, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('tipo_uni', models.CharField(max_length=1)),
                ('tipo_geo', models.CharField(blank=True, max_length=1, null=True)),
                ('fk_lugar', models.ForeignKey(blank=True, db_column='fk_lugar', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='marvel.Lugar')),
            ],
            options={
                'db_table': 'lugar',
            },
        ),
        migrations.CreateModel(
            name='PA',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=2, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=8)),
                ('fk_afili', models.ForeignKey(db_column='fk_afili', on_delete=django.db.models.deletion.DO_NOTHING, to='marvel.Afili')),
            ],
            options={
                'db_table': 'p_a',
            },
        ),
        migrations.CreateModel(
            name='Parafer',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=2, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('descrip', models.CharField(max_length=300)),
                ('tipo', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'parafer',
            },
        ),
        migrations.CreateModel(
            name='PerNoper',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=2, primary_key=True, serialize=False)),
                ('tipo_rel', models.CharField(max_length=30)),
                ('tipo_paren', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'per_noper',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=2, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('tipo', models.CharField(max_length=2)),
                ('tipo_iden', models.CharField(max_length=1)),
                ('genero', models.CharField(max_length=1)),
                ('altura', models.DecimalField(decimal_places=0, max_digits=3)),
                ('color_ojo', models.CharField(max_length=30)),
                ('biografia', models.CharField(max_length=300)),
                ('nombre_real', models.CharField(blank=True, max_length=30, null=True)),
                ('apellido_real', models.CharField(blank=True, max_length=30, null=True)),
                ('edo_civil', models.CharField(blank=True, max_length=1, null=True)),
                ('color_pelo', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'person',
            },
        ),
        migrations.CreateModel(
            name='PersonNoCombat',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=2, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('genero', models.CharField(max_length=1)),
                ('fallece', models.BooleanField()),
                ('nombre_real', models.CharField(blank=True, max_length=30, null=True)),
                ('apellido_real', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'person_no_combat',
            },
        ),
        migrations.CreateModel(
            name='Poder',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=2, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('descrip', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'poder',
            },
        ),
        migrations.CreateModel(
            name='Univer',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=2, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('descrip', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'univer',
            },
        ),
        migrations.CreateModel(
            name='AA',
            fields=[
                ('fk_parafer1', models.ForeignKey(db_column='fk_parafer1', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='Rel1_Parafer', serialize=False, to='marvel.Parafer')),
                ('fk_parafer2', models.ForeignKey(db_column='fk_parafer2', on_delete=django.db.models.deletion.DO_NOTHING, related_name='Rel2_Parafer', to='marvel.Parafer')),
            ],
            options={
                'db_table': 'a_a',
            },
        ),
        migrations.CreateModel(
            name='CP',
            fields=[
                ('fk_person', models.ForeignKey(db_column='fk_person', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='marvel.Person')),
                ('fk_catego', models.ForeignKey(db_column='fk_catego', on_delete=django.db.models.deletion.DO_NOTHING, to='marvel.Catego')),
            ],
            options={
                'db_table': 'c_p',
            },
        ),
        migrations.CreateModel(
            name='PD',
            fields=[
                ('fk_person', models.ForeignKey(db_column='fk_person', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='marvel.Person')),
                ('fk_destr', models.ForeignKey(db_column='fk_destr', on_delete=django.db.models.deletion.DO_NOTHING, to='marvel.Destr')),
            ],
            options={
                'db_table': 'p_d',
            },
        ),
        migrations.CreateModel(
            name='PPar',
            fields=[
                ('fk_person', models.ForeignKey(db_column='fk_person', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='marvel.Person')),
                ('altur_armor', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
                ('peso_armor', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
                ('fk_parafer', models.ForeignKey(db_column='fk_parafer', on_delete=django.db.models.deletion.DO_NOTHING, to='marvel.Parafer')),
            ],
            options={
                'db_table': 'p_par',
            },
        ),
        migrations.CreateModel(
            name='PPod',
            fields=[
                ('fk_person', models.ForeignKey(db_column='fk_person', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='marvel.Person')),
                ('fk_poder', models.ForeignKey(db_column='fk_poder', on_delete=django.db.models.deletion.DO_NOTHING, to='marvel.Poder')),
            ],
            options={
                'db_table': 'p_pod',
            },
        ),
        migrations.AddField(
            model_name='person',
            name='fk_lugar',
            field=models.ForeignKey(db_column='fk_lugar', on_delete=django.db.models.deletion.DO_NOTHING, to='marvel.Lugar'),
        ),
        migrations.AddField(
            model_name='person',
            name='fk_univer',
            field=models.ForeignKey(db_column='fk_univer', on_delete=django.db.models.deletion.DO_NOTHING, to='marvel.Univer'),
        ),
        migrations.AddField(
            model_name='pernoper',
            name='fk_noperson',
            field=models.ForeignKey(blank=True, db_column='fk_noperson', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='marvel.PersonNoCombat'),
        ),
        migrations.AddField(
            model_name='pernoper',
            name='fk_person',
            field=models.ForeignKey(db_column='fk_person', on_delete=django.db.models.deletion.DO_NOTHING, related_name='Rel1_PersonajeOigen', to='marvel.Person'),
        ),
        migrations.AddField(
            model_name='pernoper',
            name='fk_person_rel',
            field=models.ForeignKey(blank=True, db_column='fk_person_rel', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Rel2_PersonajeRel', to='marvel.Person'),
        ),
        migrations.AddField(
            model_name='pa',
            name='fk_person',
            field=models.ForeignKey(blank=True, db_column='fk_person', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='marvel.Person'),
        ),
        migrations.AddField(
            model_name='pa',
            name='fk_personnocombat',
            field=models.ForeignKey(blank=True, db_column='fk_personnocombat', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='marvel.PersonNoCombat'),
        ),
        migrations.AddField(
            model_name='inscri',
            name='fk_person',
            field=models.ForeignKey(db_column='fk_person', on_delete=django.db.models.deletion.DO_NOTHING, to='marvel.Person'),
        ),
        migrations.AddField(
            model_name='habili',
            name='fk_person',
            field=models.ForeignKey(db_column='fk_person', on_delete=django.db.models.deletion.DO_NOTHING, to='marvel.Person'),
        ),
        migrations.AddField(
            model_name='even',
            name='fk_lugar',
            field=models.ForeignKey(db_column='fk_lugar', on_delete=django.db.models.deletion.DO_NOTHING, to='marvel.Lugar'),
        ),
        migrations.AddField(
            model_name='combat',
            name='fk_inscri1',
            field=models.ForeignKey(blank=True, db_column='fk_inscri1', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Rel1_Inscrito1', to='marvel.Inscri'),
        ),
        migrations.AddField(
            model_name='combat',
            name='fk_inscri2',
            field=models.ForeignKey(blank=True, db_column='fk_inscri2', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Rel2_Inscrito2', to='marvel.Inscri'),
        ),
        migrations.AddField(
            model_name='afili',
            name='fk_lugar',
            field=models.ForeignKey(db_column='fk_lugar', on_delete=django.db.models.deletion.DO_NOTHING, to='marvel.Lugar'),
        ),
        migrations.AlterUniqueTogether(
            name='pernoper',
            unique_together={('id', 'fk_person')},
        ),
        migrations.AlterUniqueTogether(
            name='habili',
            unique_together={('id', 'fk_person')},
        ),
        migrations.AlterUniqueTogether(
            name='ppod',
            unique_together={('fk_person', 'fk_poder')},
        ),
        migrations.AlterUniqueTogether(
            name='ppar',
            unique_together={('fk_person', 'fk_parafer')},
        ),
        migrations.AlterUniqueTogether(
            name='pd',
            unique_together={('fk_person', 'fk_destr')},
        ),
        migrations.AlterUniqueTogether(
            name='cp',
            unique_together={('fk_person', 'fk_catego')},
        ),
        migrations.AlterUniqueTogether(
            name='aa',
            unique_together={('fk_parafer1', 'fk_parafer2')},
        ),
    ]
